fix output

diff --git a/tooling/github/get-canary-subject/action.yml b/tooling/github/get-canary-subject/action.yml
--- a/tooling/github/get-canary-subject/action.yml
+++ b/tooling/github/get-canary-subject/action.yml
@@ -3,8 +3,8 @@ description: "Gets a name used as the subject of our canary deploy (in the label
 
 outputs:
   canary-subject:
-    description: "The name used in our canary deploy.  Just the branch name with invalid characters removed."
-    value: ${{ steps.canary-subject-script.outputs.subject }}
+    description: "The name used in our canary deploy. Just the branch name with invalid characters removed."
+    value: ${{ steps.canary-subject-script.outputs.canary-subject }}
 
 runs:
   using: composite
@@ -23,4 +23,14 @@ runs:
       shell: bash
       id: canary-subject-script
       run: |
-        echo "subject=$(tsx $(dirname $GITHUB_ACTION_PATH)/index.ts)" >> $GITHUB_OUTPUT
+        tsx $(dirname $GITHUB_ACTION_PATH)/index.ts
+
+    - name: Verify Canary Subject
+      shell: bash
+      run: |
+        if [ -z "${{ steps.canary-subject-script.outputs.canary-subject }}" ]; then
+          echo "Error: Canary subject is empty or not set"
+          exit 1
+        else
+          echo "Canary subject is: ${{ steps.canary-subject-script.outputs.canary-subject }}"
+        fi
