verify canary subject

diff --git a/.github/workflows/release-canary.yml b/.github/workflows/release-canary.yml
--- a/.github/workflows/release-canary.yml
+++ b/.github/workflows/release-canary.yml
@@ -38,11 +38,19 @@ jobs:
         env:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
 
+      - name: Verify Canary Subject
+        run: |
+          if [ -z "${{ steps.get-canary-subject.outputs.canary-subject }}" ]; then
+            echo "Error: Canary subject is empty or not set"
+            exit 1
+          else
+            echo "Canary subject is: ${{ steps.get-canary-subject.outputs.canary-subject }}"
+          fi
+
       - name: Publish Canary to npm
         run: |
           pnpm changeset version --snapshot ${{ steps.get-canary-subject.outputs.canary-subject }}
           pnpm changeset publish --tag ${{ steps.get-canary-subject.outputs.canary-subject }}
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
